### PR TITLE
Feature/pori 271 kada config

### PR DESCRIPTION
**Pull request by mhernesniemi**
-Create event nodes for testing
-Flush caches
-Go to the front page and check that title, description and image fields are rendered to the event listing (Sidebars searchbox functionality is not relevant yet)

Note: If necessary, re-build the search with npm, instructions here: https://github.com/City-of-Turku/kada-elastic-events

### CODE REVIEW

**Comment by demoshane** [comment]
@mhernesniemi noticed that js and css files have changed but cannot see changed scss files, is this intentional? Code itself seems valid and assuming functionality testing is done can be approved.

minified css and js are not audited.

**Comment by demoshane** [comment]
After css cleanup commit can be approved.

**Comment by mhernesniemi** [comment]
CSS files are generated in npm builds and I would recommend to keep the CSS-files in the commits to avoid bugs. Even tho the app's scss wouldn't been changed, the dist files are generated from the whole node modules build, also SASS-version is affecting on the output. Dist folder with two files in it - bundle.js and style.css are the only files that Drupal loads.

**Comment by demoshane** [comment]
Approved.

**Pull request merged**
